# Generated by Django 5.0.1 on 2024-03-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments2',
            new_name='Callus',
        ),
    ]
