# Generated by Django 5.0.1 on 2024-03-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_rename_comments2_callus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo')),
                ('title', models.CharField(max_length=50)),
                ('discribtion', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
