# Generated by Django 5.0.1 on 2024-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
