# Generated by Django 5.0.1 on 2024-03-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_expertdoctor_delete_likes_alter_blogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertdoctor',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
